<?= $this->doctype() ?>

<html lang="en">
<head>

    <meta charset="utf-8" />

    <?= $this->headTitle('SOA Project')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- CSS -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
//    <!--  Custom CSS -->
        ->prependStylesheet($this->basePath('assets/css/style.css'))
        ->prependStylesheet($this->basePath('assets/css/helper.css'))
//        ->prependStylesheet($this->basePath('assets/css/lib/owl.theme.default.min.css'))
//        ->prependStylesheet($this->basePath('assets/css/lib/owl.carousel.min.css'))
//        ->prependStylesheet($this->basePath('assets/css/lib/calendar2/pignose.calendar.min.css'))
//        ->prependStylesheet($this->basePath('assets/css/lib/calendar2/semantic.ui.min.css'))
//    <!-- Bootstrap core CSS     -->
        ->prependStylesheet($this->basePath('assets/css/lib/bootstrap/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('assets/js/custom.min.js'))
//        ->prependFile($this->basePath('assets/js/scripts.js'))
//        ->prependFile($this->basePath('assets/js/lib/owl-carousel/owl.carousel-init.js'))
//        ->prependFile($this->basePath('assets/js/lib/owl-carousel/owl.carousel.min.js'))
//        ->prependFile($this->basePath('assets/js/lib/calendar-2/pignose.calendar.min.js'))
//        ->prependFile($this->basePath('assets/js/lib/calendar-2/prism.min.js'))
//        ->prependFile($this->basePath('assets/js/lib/calendar-2/semantic.ui.min.js'))
//        ->prependFile($this->basePath('assets/js/lib/calendar-2/moment.latest.min.js'))
//        ->prependFile($this->basePath('assets/js/lib/morris-chart/dashboard1-init.js'))
//        ->prependFile($this->basePath('assets/js/lib/morris-chart/morris.js'))
//        ->prependFile($this->basePath('assets/js/lib/morris-chart/raphael-min.js'))
//    <!-- stickey kit -->
        ->prependFile($this->basePath('assets/js/lib/sticky-kit-master/dist/sticky-kit.min.js'))
//    <!-- Menu sideba -->
        ->prependFile($this->basePath('assets/js/sidebarmenu.js'))
//    <!--  slimscrollbar scrollbar JavaScript   -->
        ->prependFile($this->basePath('assets/js/jquery.slimscroll.js'))
//    <!--   Bootstrap tether Core JavaScript   -->
        ->prependFile($this->basePath('assets/js/lib/bootstrap/js/bootstrap.min.js'))
        ->prependFile($this->basePath('assets/js/lib/bootstrap/js/popper.min.js'))
//    <!--   All Jquery   -->
        ->prependFile($this->basePath('assets/js/lib/jquery/jquery.min.js'))
    ?>
</head>
<body class="fix-header fix-sidebar">
<!-- Preloader - style you can find in spinners.css -->
<div class="preloader">
    <svg class="circular" viewBox="25 25 50 50">
        <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" /> </svg>
</div>
<!-- Main wrapper  -->
<div id="main-wrapper">
    <!-- header header  -->
    <div class="header">
        <nav class="navbar top-navbar navbar-expand-md navbar-light">
            <!-- Logo -->
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html">
                    <!-- Logo icon -->
                    <b><img src="<?=$this->basePath('assets/images/logo.png') ?>" alt="homepage" class="dark-logo" /></b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span>Sistema</span>
                </a>
            </div>
            <!-- End Logo -->
            <div class="navbar-collapse">
                <!-- toggle and nav items -->
                <ul class="navbar-nav mr-auto mt-md-0">
                    <!-- This is  -->
                    <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted  " href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                    <li class="nav-item m-l-10"> <a class="nav-link sidebartoggler hidden-sm-down text-muted  " href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                </ul>
                    <li class="nav-item">
                        <a class="fa fa-power-off" href="#" aria-haspopup="true" aria-expanded="false"> Sair</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <!-- End header header -->
    <!-- Left Sidebar  -->
    <div class="left-sidebar">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li class="nav-devider"></li>
                    <li class="nav-label">Home</li>
                    <li> <a class="has-arrow" href="#" aria-expanded="false"><i class="ti-user"></i><span class="hide-menu">Usuários </span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="#">Médicos </a></li>
                            <li><a href="#">Pacientes </a></li>
                        </ul>
                    </li>
                    <li class="nav-label">Apps</li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-envelope"></i><span class="hide-menu">Email</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="email-compose.html">Compose</a></li>
                            <li><a href="email-read.html">Read</a></li>
                            <li><a href="email-inbox.html">Inbox</a></li>
                        </ul>
                    </li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-bar-chart"></i><span class="hide-menu">Charts</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="chart-flot.html">Flot</a></li>
                            <li><a href="chart-morris.html">Morris</a></li>
                            <li><a href="chart-chartjs.html">ChartJs</a></li>
                            <li><a href="chart-chartist.html">Chartist </a></li>
                            <li><a href="chart-amchart.html">AmChart</a></li>
                            <li><a href="chart-echart.html">EChart</a></li>
                            <li><a href="chart-sparkline.html">Sparkline</a></li>
                            <li><a href="chart-peity.html">Peity</a></li>
                        </ul>
                    </li>
                    <li class="nav-label">Features</li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-suitcase"></i><span class="hide-menu">Bootstrap UI <span class="label label-rouded label-warning pull-right">6</span></span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="ui-alert.html">Alert</a></li>
                            <li><a href="ui-button.html">Button</a></li>
                            <li><a href="ui-dropdown.html">Dropdown</a></li>
                            <li><a href="ui-progressbar.html">Progressbar</a></li>
                            <li><a href="ui-tab.html">Tab</a></li>
                            <li><a href="ui-typography.html">Typography</a></li>
                        </ul>
                    </li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-suitcase"></i><span class="hide-menu">Components <span class="label label-rouded label-danger pull-right">6</span></span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="uc-calender.html">Calender</a></li>
                            <li><a href="uc-datamap.html">Datamap</a></li>
                            <li><a href="uc-nestedable.html">Nestedable</a></li>
                            <li><a href="uc-sweetalert.html">Sweetalert</a></li>
                            <li><a href="uc-toastr.html">Toastr</a></li>
                            <li><a href="uc-weather.html">Weather</a></li>
                        </ul>
                    </li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-wpforms"></i><span class="hide-menu">Forms</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="form-basic.html">Basic Forms</a></li>
                            <li><a href="form-layout.html">Form Layout</a></li>
                            <li><a href="form-validation.html">Form Validation</a></li>
                            <li><a href="form-editor.html">Editor</a></li>
                            <li><a href="form-dropzone.html">Dropzone</a></li>
                        </ul>
                    </li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-table"></i><span class="hide-menu">Tables</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="table-bootstrap.html">Basic Tables</a></li>
                            <li><a href="table-datatable.html">Data Tables</a></li>
                        </ul>
                    </li>
                    <li class="nav-label">Layout</li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-columns"></i><span class="hide-menu">Layout</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="layout-blank.html">Blank</a></li>
                            <li><a href="layout-boxed.html">Boxed</a></li>
                            <li><a href="layout-fix-header.html">Fix Header</a></li>
                            <li><a href="layout-fix-sidebar.html">Fix Sidebar</a></li>
                        </ul>
                    </li>
                    <li class="nav-label">EXTRA</li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-book"></i><span class="hide-menu">Pages <span class="label label-rouded label-success pull-right">8</span></span></a>
                        <ul aria-expanded="false" class="collapse">

                            <li><a href="#" class="has-arrow">Authentication <span class="label label-rounded label-success">6</span></a>
                                <ul aria-expanded="false" class="collapse">
                                    <li><a href="page-login.html">Login</a></li>
                                    <li><a href="page-register.html">Register</a></li>
                                    <li><a href="page-invoice.html">Invoice</a></li>
                                </ul>
                            </li>
                            <li><a href="#" class="has-arrow">Error Pages</a>
                                <ul aria-expanded="false" class="collapse">
                                    <li><a href="page-error-400.html">400</a></li>
                                    <li><a href="page-error-403.html">403</a></li>
                                    <li><a href="page-error-404.html">404</a></li>
                                    <li><a href="page-error-500.html">500</a></li>
                                    <li><a href="page-error-503.html">503</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-map-marker"></i><span class="hide-menu">Maps</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="map-google.html">Google</a></li>
                            <li><a href="map-vector.html">Vector</a></li>
                        </ul>
                    </li>
                    <li> <a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-level-down"></i><span class="hide-menu">Multi level dd</span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li><a href="#">item 1.1</a></li>
                            <li><a href="#">item 1.2</a></li>
                            <li> <a class="has-arrow" href="#" aria-expanded="false">Menu 1.3</a>
                                <ul aria-expanded="false" class="collapse">
                                    <li><a href="#">item 1.3.1</a></li>
                                    <li><a href="#">item 1.3.2</a></li>
                                    <li><a href="#">item 1.3.3</a></li>
                                    <li><a href="#">item 1.3.4</a></li>
                                </ul>
                            </li>
                            <li><a href="#">item 1.4</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </div>
    <!-- End Left Sidebar  -->
    <!-- Page wrapper  -->
    <div class="page-wrapper">
        <!-- Container fluid  -->
        <div class="container-fluid">
            <!-- Start Page Content -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="content">
                                <div class="container-fluid">
                                    <?= $this->content ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End PAge Content -->
        </div>
        <!-- End Container fluid  -->
        <!-- footer -->
        <footer class="footer"> © 2018 All rights reserved. Template designed by <a href="https://colorlib.com">Colorlib</a></footer>
        <!-- End footer -->
    </div>
    <!-- End Page wrapper  -->
</div>
<!-- End Wrapper -->
</body>

</html>
