<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Sistema MED +')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->

    <!-- Favicon-->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

        //Custom CSS
        ->prependStylesheet($this->basePath('css/custom.css'))
        //Theme Stylesheet
        ->prependStylesheet($this->basePath('css/style.blue.css'), 'screen',true,['id' => 'theme-stylesheet'])
        //Custom Scroll Bar
        ->prependStylesheet($this->basePath('vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.css'))
        //JQuery Circle
        ->prependStylesheet($this->basePath('css/grasp_mobile_progress_circle-1.0.0.min.css'))
        //Google fonts - Roboto
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Roboto:300,400,500,700')
        //Fontastic Custom icon font
        ->prependStylesheet($this->basePath('css/fontastic.css'))
        //Font Awesome CSS
        ->prependStylesheet($this->basePath('vendor/font-awesome/css/font-awesome.min.css'))
        //Bootstrap CSS
        ->prependStylesheet($this->basePath('vendor/bootstrap/css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js')
        ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js')
        ->prependFile($this->basePath('js/front.js'))
//        ->prependFile($this->basePath('js/charts-home.js'))
        ->prependFile($this->basePath('vendor/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js'))
        ->prependFile($this->basePath('vendor/jquery-validation/jquery.validate.min.js'))
        ->prependFile($this->basePath('vendor/chart.js/Chart.min.js'))
        ->prependFile($this->basePath('vendor/jquery.cookie/jquery.cookie.js'))
        ->prependFile($this->basePath('js/grasp_mobile_progress_circle-1.0.0.min.js'))
        ->prependFile($this->basePath('vendor/bootstrap/js/bootstrap.min.js'))
        ->prependFile($this->basePath('vendor/popper.js/umd/popper.min.js'))
        ->prependFile($this->basePath('vendor/jquery/jquery.min.js'))

    ?>
</head>
<body>
<!-- Side Navbar -->
<nav class="side-navbar">
    <div class="side-navbar-wrapper">
        <!-- Sidebar Header    -->
        <div class="sidenav-header d-flex align-items-center justify-content-center">
            <!-- User Info-->
            <div class="sidenav-header-inner text-center"><img src="img/avatar-7.jpg" alt="person" class="img-fluid rounded-circle">
                <h2 class="h5">Nathan Andrews</h2><span>Web Developer</span>
            </div>
            <!-- Small Brand information, appears on minimized sidebar-->
            <div class="sidenav-header-logo"><a href="index.html" class="brand-small text-center"> <strong>SOA</strong><strong class="text-primary">P</strong></a></div>
        </div>
        <!-- Sidebar Navigation Menus-->
        <div class="main-menu">
            <ul id="side-main-menu" class="side-menu list-unstyled">
                <li><a href="<?=$this->url('home')?>"> <i class="icon-home"></i>Home                             </a></li>
                <li><a href="#user" aria-expanded="false" data-toggle="collapse"> <i class="icon-user"></i>Usuários </a>
                    <ul id="user" class="collapse list-unstyled ">
                        <li><a href="#userAdmin" aria-expanded="false" data-toggle="collapse">Administrador </a>
                            <ul id="userAdmin" class="collapse list-unstyled ">
                                <li><a href="/user/administrator">Listar</a></li>
                                <li><a href="/user/administrator/add">Adicionar</a></li>
                            </ul>
                        </li>
                        <li><a href="#userClerk" aria-expanded="false" data-toggle="collapse">Atendente </a>
                            <ul id="userClerk" class="collapse list-unstyled ">
                                <li><a href="/user/clerk">Listar</a></li>
                                <li><a href="/user/clerk/add">Adicionar</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li><a href="#exam" aria-expanded="false" data-toggle="collapse"> <i class="icon-form"></i>Exames </a>
                    <ul id="exam" class="collapse list-unstyled ">
                        <li><a href="/exam">Listar</a></li>
                        <li><a href="/exam/add">Adicionar</a></li>
                        <li><a href="#category" aria-expanded="false" data-toggle="collapse"> <i class="icon-flask"></i>Categoria </a>
                            <ul id="category" class="collapse list-unstyled ">
                                <li><a href="/category">Listar</a></li>
                                <li><a href="/category/add">Adicionar</a></li>
                            </ul>
                        </li>
                    </ul>
                <li><a href="#patient" aria-expanded="false" data-toggle="collapse"> <i class="icon-pencil-case"></i>Pacientes </a>
                    <ul id="patient" class="collapse list-unstyled ">
                        <li><a href="/patient">Listar</a></li>
                        <li><a href="/patient/add">Adicionar</a></li>
                    </ul>
                </li>
                <li><a href="#budget" aria-expanded="false" data-toggle="collapse"> <i class="icon-padnote"></i>Orçamentos </a>
                    <ul id="budget" class="collapse list-unstyled ">
                        <li><a href="/budget">Listar</a></li>
                        <li><a href="/budget/add">Adicionar</a></li>
                    </ul>
                </li>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="page">
    <!-- navbar-->

    <header class="header">
        <nav class="navbar">
            <div class="container-fluid">
                <div class="navbar-holder d-flex align-items-center justify-content-between">
                    <div class="navbar-header"><a id="toggle-btn" href="#" class="menu-btn">
                            <i class="icon-bars"> </i></a><a href="/home" class="navbar-brand">
                            <div class="brand-text d-none d-md-inline-block"><strong class="text-primary">&nbsp;</strong></div></a>
                    </div>
                    <ul class="nav-menu list-unstyled d-flex flex-md-row align-items-md-center">
                        <!-- Log out-->
<!--                        <li class="nav-item"><a href="--><?php //echo $this->url('zfcuser/logout');?><!--" class="nav-link logout"> <span class="d-none d-sm-inline-block">Sair</span><i class="fa fa-sign-out"></i></a></li>-->
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <section class="mt-30px mb-30px">
        <div class="container-fluid">
            <!-- CONTENT -->
            <?php echo $this->content . PHP_EOL; ?>
            <!-- CONTENT -->

        </div>
    </section>

    <footer class="main-footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 text-right">
                    <p>&copy; 2016 - <?= date('Y') ?> by Med+ All rights reserved.</p>
                </div>
            </div>
        </div>
    </footer>
</div>
</body>
</html>